export type tGroup = {
      "id": number, 
      "name": string | number,
      "avgPrice": number ,
      "maxPrice": number ,
      "minPrice": number,
  }[];




export const developers = [
    {
        "avg_negative_rating": 7.05,
        "avg_positive_rating": 51.11,
        "avg_price": 3.85,
        "developer_id": 1915,
        "developer_name": "Choice of Games123",
        "game_count": 94,
        "max_negative_rating": 50,
        "max_positive_rating": 1719,
        "max_price": 5.19,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 2.09
    },
    {
        "avg_negative_rating": 240.71,
        "avg_positive_rating": 555.63,
        "avg_price": 20.04,
        "developer_id": 1547,
        "developer_name": "KOEI TECMO GAMES CO., LTD.",
        "game_count": 72,
        "max_negative_rating": 4620,
        "max_positive_rating": 9842,
        "max_price": 44.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": -10
    },
    {
        "avg_negative_rating": 8.73,
        "avg_positive_rating": 13.08,
        "avg_price": 8.7,
        "developer_id": 8105,
        "developer_name": "Ripknot Systems",
        "game_count": 62,
        "max_negative_rating": 61,
        "max_positive_rating": 40,
        "max_price": 24.99,
        "min_negative_rating": 0,
        "min_positive_rating": 1,
        "min_price": 4.99
    },
    {
        "avg_negative_rating": 5.35,
        "avg_positive_rating": 9.92,
        "avg_price": 1.82,
        "developer_id": 9084,
        "developer_name": "Laush Dmitriy Sergeevich",
        "game_count": 51,
        "max_negative_rating": 33,
        "max_positive_rating": 60,
        "max_price": 4.79,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0.79
    },
    {
        "avg_negative_rating": 11.7,
        "avg_positive_rating": 20.68,
        "avg_price": 1.17,
        "developer_id": 10241,
        "developer_name": "Nikita \"Ghost_RUS\"",
        "game_count": 50,
        "max_negative_rating": 39,
        "max_positive_rating": 102,
        "max_price": 4.79,
        "min_negative_rating": 0,
        "min_positive_rating": 1,
        "min_price": 0.79
    },
    {
        "avg_negative_rating": 12.6,
        "avg_positive_rating": 5.24,
        "avg_price": 0.89,
        "developer_id": 11248,
        "developer_name": "Dexion Games",
        "game_count": 45,
        "max_negative_rating": 37,
        "max_positive_rating": 19,
        "max_price": 2.09,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0.79
    },
    {
        "avg_negative_rating": 16.51,
        "avg_positive_rating": 34.84,
        "avg_price": 0.96,
        "developer_id": 11412,
        "developer_name": "RewindApp",
        "game_count": 43,
        "max_negative_rating": 131,
        "max_positive_rating": 344,
        "max_price": 3.99,
        "min_negative_rating": 1,
        "min_positive_rating": 1,
        "min_price": 0.79
    },
    {
        "avg_negative_rating": 5.36,
        "avg_positive_rating": 36.76,
        "avg_price": 3.29,
        "developer_id": 3779,
        "developer_name": "Hosted Games",
        "game_count": 42,
        "max_negative_rating": 26,
        "max_positive_rating": 241,
        "max_price": 5.79,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 2.09
    },
    {
        "avg_negative_rating": 8.53,
        "avg_positive_rating": 26.13,
        "avg_price": 0.79,
        "developer_id": 9121,
        "developer_name": "Blender Games",
        "game_count": 40,
        "max_negative_rating": 72,
        "max_positive_rating": 316,
        "max_price": 0.79,
        "min_negative_rating": 0,
        "min_positive_rating": 1,
        "min_price": 0.79
    },
    {
        "avg_negative_rating": 8.36,
        "avg_positive_rating": 93.39,
        "avg_price": 4.71,
        "developer_id": 1177,
        "developer_name": "Humongous Entertainment",
        "game_count": 36,
        "max_negative_rating": 46,
        "max_positive_rating": 580,
        "max_price": 4.99,
        "min_negative_rating": 0,
        "min_positive_rating": 11,
        "min_price": 3.99
    },
    {
        "avg_negative_rating": 6.53,
        "avg_positive_rating": 31.78,
        "avg_price": 1.57,
        "developer_id": 11092,
        "developer_name": "For Kids",
        "game_count": 36,
        "max_negative_rating": 24,
        "max_positive_rating": 121,
        "max_price": 7.19,
        "min_negative_rating": 0,
        "min_positive_rating": 1,
        "min_price": 0
    },
    {
        "avg_negative_rating": 36.46,
        "avg_positive_rating": 41.77,
        "avg_price": 1.62,
        "developer_id": 5878,
        "developer_name": "EnsenaSoft",
        "game_count": 35,
        "max_negative_rating": 72,
        "max_positive_rating": 176,
        "max_price": 4.79,
        "min_negative_rating": 2,
        "min_positive_rating": 0,
        "min_price": 0
    },
    {
        "avg_negative_rating": 0.47,
        "avg_positive_rating": 2.75,
        "avg_price": 7.44,
        "developer_id": 5981,
        "developer_name": "Eipix Entertainment",
        "game_count": 32,
        "max_negative_rating": 3,
        "max_positive_rating": 8,
        "max_price": 10.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 6.99
    },
    {
        "avg_negative_rating": 18.56,
        "avg_positive_rating": 10.28,
        "avg_price": 0.79,
        "developer_id": 14160,
        "developer_name": "Nekyau Games",
        "game_count": 32,
        "max_negative_rating": 53,
        "max_positive_rating": 61,
        "max_price": 0.79,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0.79
    },
    {
        "avg_negative_rating": 8.35,
        "avg_positive_rating": 16.35,
        "avg_price": 4.52,
        "developer_id": 2715,
        "developer_name": "Warfare Studios",
        "game_count": 31,
        "max_negative_rating": 24,
        "max_positive_rating": 76,
        "max_price": 6.99,
        "min_negative_rating": 0,
        "min_positive_rating": 1,
        "min_price": 2.09
    },
    {
        "avg_negative_rating": 6.33,
        "avg_positive_rating": 26.33,
        "avg_price": 7.08,
        "developer_id": 295,
        "developer_name": "HeR Interactive",
        "game_count": 30,
        "max_negative_rating": 30,
        "max_positive_rating": 68,
        "max_price": 15.49,
        "min_negative_rating": 1,
        "min_positive_rating": 3,
        "min_price": 4.99
    },
    {
        "avg_negative_rating": 20,
        "avg_positive_rating": 65.14,
        "avg_price": 6.61,
        "developer_id": 185,
        "developer_name": "MumboJumbo",
        "game_count": 29,
        "max_negative_rating": 44,
        "max_positive_rating": 244,
        "max_price": 9.99,
        "min_negative_rating": 3,
        "min_positive_rating": 6,
        "min_price": 4.99
    },
    {
        "avg_negative_rating": 0.54,
        "avg_positive_rating": 1.75,
        "avg_price": 7.17,
        "developer_id": 5976,
        "developer_name": "ERS G Studios",
        "game_count": 28,
        "max_negative_rating": 3,
        "max_positive_rating": 6,
        "max_price": 10.29,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 4.99
    },
    {
        "avg_negative_rating": 7967.21,
        "avg_positive_rating": 87624.11,
        "avg_price": 4.98,
        "developer_id": 1,
        "developer_name": "Valve",
        "game_count": 28,
        "max_negative_rating": 142079,
        "max_positive_rating": 863507,
        "max_price": 15.99,
        "min_negative_rating": 145,
        "min_positive_rating": 1273,
        "min_price": 0
    },
    {
        "avg_negative_rating": 206.89,
        "avg_positive_rating": 379.82,
        "avg_price": 3.7,
        "developer_id": 2914,
        "developer_name": "Creobit",
        "game_count": 28,
        "max_negative_rating": 5411,
        "max_positive_rating": 9693,
        "max_price": 3.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0
    }
];

export const publishers = [
    {
        "avg_negative_rating": 1.07,
        "avg_positive_rating": 4.44,
        "avg_price": 6.83,
        "game_count": 212,
        "max_negative_rating": 34,
        "max_positive_rating": 87,
        "max_price": 10.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 2.79,
        "publisher_id": 56,
        "publisher_name": "Big Fish Games"
    },
    {
        "avg_negative_rating": 82.78,
        "avg_positive_rating": 227.6,
        "avg_price": 7.64,
        "game_count": 136,
        "max_negative_rating": 2981,
        "max_positive_rating": 10465,
        "max_price": 34.95,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0,
        "publisher_id": 6,
        "publisher_name": "Strategy First"
    },
    {
        "avg_negative_rating": 2256.65,
        "avg_positive_rating": 8112.81,
        "avg_price": 16.48,
        "game_count": 111,
        "max_negative_rating": 59620,
        "max_positive_rating": 251178,
        "max_price": 49.99,
        "min_negative_rating": 1,
        "min_positive_rating": 4,
        "min_price": 0,
        "publisher_id": 10,
        "publisher_name": "Ubisoft"
    },
    {
        "avg_negative_rating": 290,
        "avg_positive_rating": 1031.49,
        "avg_price": 12.85,
        "game_count": 98,
        "max_negative_rating": 2486,
        "max_positive_rating": 10566,
        "max_price": 44.99,
        "min_negative_rating": 1,
        "min_positive_rating": 10,
        "min_price": 0,
        "publisher_id": 20,
        "publisher_name": "THQ Nordic"
    },
    {
        "avg_negative_rating": 820.36,
        "avg_positive_rating": 3092.36,
        "avg_price": 12.1,
        "game_count": 97,
        "max_negative_rating": 14024,
        "max_positive_rating": 39387,
        "max_price": 44.99,
        "min_negative_rating": 2,
        "min_positive_rating": 10,
        "min_price": 0,
        "publisher_id": 53,
        "publisher_name": "Square Enix"
    },
    {
        "avg_negative_rating": 48.08,
        "avg_positive_rating": 855.74,
        "avg_price": 9.82,
        "game_count": 96,
        "max_negative_rating": 765,
        "max_positive_rating": 16160,
        "max_price": 30.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0,
        "publisher_id": 918,
        "publisher_name": "Sekai Project"
    },
    {
        "avg_negative_rating": 7.05,
        "avg_positive_rating": 51.11,
        "avg_price": 3.85,
        "game_count": 94,
        "max_negative_rating": 50,
        "max_positive_rating": 1719,
        "max_price": 5.19,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 2.09,
        "publisher_id": 1296,
        "publisher_name": "Choice of Games"
    },
    {
        "avg_negative_rating": 88.27,
        "avg_positive_rating": 359.61,
        "avg_price": 6.19,
        "game_count": 88,
        "max_negative_rating": 2025,
        "max_positive_rating": 11389,
        "max_price": 27.79,
        "min_negative_rating": 2,
        "min_positive_rating": 4,
        "min_price": 0,
        "publisher_id": 26,
        "publisher_name": "1C Entertainment"
    },
    {
        "avg_negative_rating": 65.66,
        "avg_positive_rating": 97.06,
        "avg_price": 2.7,
        "game_count": 88,
        "max_negative_rating": 997,
        "max_positive_rating": 2087,
        "max_price": 3.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0.79,
        "publisher_id": 2094,
        "publisher_name": "Dagestan Technology"
    },
    {
        "avg_negative_rating": 674.47,
        "avg_positive_rating": 3047.42,
        "avg_price": 13.31,
        "game_count": 78,
        "max_negative_rating": 13423,
        "max_positive_rating": 31864,
        "max_price": 49.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0,
        "publisher_id": 38,
        "publisher_name": "SEGA"
    },
    {
        "avg_negative_rating": 35.74,
        "avg_positive_rating": 362.55,
        "avg_price": 12.47,
        "game_count": 77,
        "max_negative_rating": 425,
        "max_positive_rating": 10985,
        "max_price": 60.99,
        "min_negative_rating": 0,
        "min_positive_rating": 3,
        "min_price": 1.59,
        "publisher_id": 507,
        "publisher_name": "Degica"
    },
    {
        "avg_negative_rating": 27.18,
        "avg_positive_rating": 77.11,
        "avg_price": 6.38,
        "game_count": 72,
        "max_negative_rating": 652,
        "max_positive_rating": 1498,
        "max_price": 29.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0,
        "publisher_id": 817,
        "publisher_name": "Plug In Digital"
    },
    {
        "avg_negative_rating": 49.23,
        "avg_positive_rating": 156.83,
        "avg_price": 22.23,
        "game_count": 71,
        "max_negative_rating": 389,
        "max_positive_rating": 1054,
        "max_price": 60.99,
        "min_negative_rating": 0,
        "min_positive_rating": 2,
        "min_price": 0,
        "publisher_id": 286,
        "publisher_name": "Slitherine Ltd."
    },
    {
        "avg_negative_rating": 265.18,
        "avg_positive_rating": 558.96,
        "avg_price": 20.13,
        "game_count": 71,
        "max_negative_rating": 4620,
        "max_positive_rating": 9842,
        "max_price": 44.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": -10,
        "publisher_id": 748,
        "publisher_name": "KOEI TECMO GAMES CO., LTD."
    },
    {
        "avg_negative_rating": 188.61,
        "avg_positive_rating": 204.23,
        "avg_price": 5.78,
        "game_count": 71,
        "max_negative_rating": 2295,
        "max_positive_rating": 1288,
        "max_price": 22.99,
        "min_negative_rating": 0,
        "min_positive_rating": 3,
        "min_price": 0,
        "publisher_id": 798,
        "publisher_name": "KISS ltd"
    },
    {
        "avg_negative_rating": 59.35,
        "avg_positive_rating": 462.9,
        "avg_price": 5.9,
        "game_count": 69,
        "max_negative_rating": 534,
        "max_positive_rating": 5904,
        "max_price": 19.49,
        "min_negative_rating": 0,
        "min_positive_rating": 1,
        "min_price": 0,
        "publisher_id": 569,
        "publisher_name": "AGM PLAYISM"
    },
    {
        "avg_negative_rating": 37.66,
        "avg_positive_rating": 226.6,
        "avg_price": 7.91,
        "game_count": 67,
        "max_negative_rating": 299,
        "max_positive_rating": 1099,
        "max_price": 11.39,
        "min_negative_rating": 0,
        "min_positive_rating": 8,
        "min_price": 6.99,
        "publisher_id": 834,
        "publisher_name": "Artifex Mundi"
    },
    {
        "avg_negative_rating": 38.21,
        "avg_positive_rating": 100.53,
        "avg_price": 4.79,
        "game_count": 66,
        "max_negative_rating": 280,
        "max_positive_rating": 996,
        "max_price": 14.99,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0.79,
        "publisher_id": 72,
        "publisher_name": "Buka Entertainment"
    },
    {
        "avg_negative_rating": 538.91,
        "avg_positive_rating": 4496.92,
        "avg_price": 9.65,
        "game_count": 65,
        "max_negative_rating": 8556,
        "max_positive_rating": 45809,
        "max_price": 34.99,
        "min_negative_rating": 2,
        "min_positive_rating": 4,
        "min_price": 0,
        "publisher_id": 212,
        "publisher_name": "Devolver Digital"
    },
    {
        "avg_negative_rating": 28.95,
        "avg_positive_rating": 71.47,
        "avg_price": 2.11,
        "game_count": 64,
        "max_negative_rating": 193,
        "max_positive_rating": 1005,
        "max_price": 7.19,
        "min_negative_rating": 0,
        "min_positive_rating": 0,
        "min_price": 0.79,
        "publisher_id": 3452,
        "publisher_name": "Atriagames"
    }
];