
const games = [
    {
        "id": 1,
        "Название": "Counter-Strike",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Online Multi-Player, Local Multi-Player, Valve Anti-Cheat enabled",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 124534,
        "Количество отрицательных отзывов": 3339
    },
    {
        "id": 2,
        "Название": "Team Fortress Classic",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Online Multi-Player, Local Multi-Player, Valve Anti-Cheat enabled",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 3318,
        "Количество отрицательных отзывов": 633
    },
    {
        "id": 3,
        "Название": "Day of Defeat",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 3416,
        "Количество отрицательных отзывов": 398
    },
    {
        "id": 4,
        "Название": "Deathmatch Classic",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Online Multi-Player, Local Multi-Player, Valve Anti-Cheat enabled",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 1273,
        "Количество отрицательных отзывов": 267
    },
    {
        "id": 5,
        "Название": "Half-Life: Opposing Force",
        "Издатель": "Valve",
        "Разработчик": "Gearbox Software",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 5250,
        "Количество отрицательных отзывов": 288
    },
    {
        "id": 6,
        "Название": "Ricochet",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Online Multi-Player, Valve Anti-Cheat enabled",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 2758,
        "Количество отрицательных отзывов": 684
    },
    {
        "id": 7,
        "Название": "Half-Life",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Online Multi-Player, Valve Anti-Cheat enabled, Single-player, Steam Cloud",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 27755,
        "Количество отрицательных отзывов": 1100
    },
    {
        "id": 8,
        "Название": "Counter-Strike: Condition Zero",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 12120,
        "Количество отрицательных отзывов": 1439
    },
    {
        "id": 9,
        "Название": "Half-Life: Blue Shift",
        "Издатель": "Valve",
        "Разработчик": "Gearbox Software",
        "Категории": "Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 3822,
        "Количество отрицательных отзывов": 420
    },
    {
        "id": 10,
        "Название": "Half-Life 2",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player, Steam Cloud, Steam Achievements, Steam Trading Cards, Captions available, Partial Controller Support, Includes Source SDK",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 67902,
        "Количество отрицательных отзывов": 2419
    },
    {
        "id": 11,
        "Название": "Counter-Strike: Source",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Steam Cloud, Steam Achievements, Includes Source SDK, Cross-Platform Multiplayer, Stats",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 76640,
        "Количество отрицательных отзывов": 3497
    },
    {
        "id": 12,
        "Название": "Half-Life: Source",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 0,
        "Количество положительных отзывов": 3767,
        "Количество отрицательных отзывов": 1053
    },
    {
        "id": 13,
        "Название": "Day of Defeat: Source",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Steam Achievements, Steam Trading Cards, Includes Source SDK, Cross-Platform Multiplayer, Stats",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 10489,
        "Количество отрицательных отзывов": 1210
    },
    {
        "id": 14,
        "Название": "Half-Life 2: Deathmatch",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Includes Source SDK",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 6020,
        "Количество отрицательных отзывов": 787
    },
    {
        "id": 15,
        "Название": "Half-Life 2: Lost Coast",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player, Commentary available",
        "Платформы": "windows, mac, linux",
        "Цена": 0,
        "Количество положительных отзывов": 5783,
        "Количество отрицательных отзывов": 1020
    },
    {
        "id": 16,
        "Название": "Half-Life Deathmatch: Source",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled",
        "Платформы": "windows, mac, linux",
        "Цена": 0,
        "Количество положительных отзывов": 1362,
        "Количество отрицательных отзывов": 473
    },
    {
        "id": 17,
        "Название": "Half-Life 2: Episode One",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player, Steam Cloud, Steam Achievements, Captions available, Partial Controller Support, Includes Source SDK, Stats, Commentary available",
        "Платформы": "windows, mac, linux",
        "Цена": 5.79,
        "Количество положительных отзывов": 7908,
        "Количество отрицательных отзывов": 517
    },
    {
        "id": 18,
        "Название": "Portal",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player, Steam Achievements, Captions available, Partial Controller Support, Includes Source SDK, Commentary available, Includes level editor",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 51801,
        "Количество отрицательных отзывов": 1080
    },
    {
        "id": 19,
        "Название": "Half-Life 2: Episode Two",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player, Steam Cloud, Steam Achievements, Captions available, Partial Controller Support, Includes Source SDK, Stats, Commentary available",
        "Платформы": "windows, mac, linux",
        "Цена": 5.79,
        "Количество положительных отзывов": 13902,
        "Количество отрицательных отзывов": 696
    },
    {
        "id": 20,
        "Название": "Team Fortress 2",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Steam Achievements, Steam Trading Cards, Captions available, Partial Controller Support, Cross-Platform Multiplayer, Stats, Commentary available, Includes level editor, Steam Workshop, In-App Purchases",
        "Платформы": "windows, mac, linux",
        "Цена": 0,
        "Количество положительных отзывов": 515879,
        "Количество отрицательных отзывов": 34036
    },
    {
        "id": 21,
        "Название": "Left 4 Dead",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player, Steam Cloud, Steam Achievements, Captions available, Includes Source SDK, Stats, Commentary available, Co-op, Full controller support, Steam Leaderboards",
        "Платформы": "windows, mac",
        "Цена": 7.19,
        "Количество положительных отзывов": 17951,
        "Количество отрицательных отзывов": 948
    },
    {
        "id": 22,
        "Название": "Left 4 Dead 2",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player, Steam Cloud, Steam Achievements, Steam Trading Cards, Captions available, Includes Source SDK, Stats, Commentary available, Steam Workshop, Co-op, Full controller support",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 251789,
        "Количество отрицательных отзывов": 8418
    },
    {
        "id": 23,
        "Название": "Dota 2",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Steam Trading Cards, Steam Workshop, In-App Purchases, Co-op, SteamVR Collectibles",
        "Платформы": "windows, mac, linux",
        "Цена": 0,
        "Количество положительных отзывов": 863507,
        "Количество отрицательных отзывов": 142079
    },
    {
        "id": 24,
        "Название": "Portal 2",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Single-player, Steam Cloud, Steam Achievements, Steam Trading Cards, Captions available, Stats, Commentary available, Includes level editor, Steam Workshop, Co-op, Full controller support",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 138220,
        "Количество отрицательных отзывов": 1891
    },
    {
        "id": 25,
        "Название": "Alien Swarm",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Multi-player, Single-player, Steam Cloud, Steam Achievements, Captions available, Stats, Includes level editor, Co-op",
        "Платформы": "windows",
        "Цена": 0,
        "Количество положительных отзывов": 17435,
        "Количество отрицательных отзывов": 941
    },
    {
        "id": 26,
        "Название": "Counter-Strike: Global Offensive",
        "Издатель": "Valve",
        "Разработчик": "Valve;Hidden Path Entertainment",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Steam Achievements, Steam Trading Cards, Stats, Steam Workshop, In-App Purchases, Full controller support",
        "Платформы": "windows, mac, linux",
        "Цена": 0,
        "Количество положительных отзывов": 2644404,
        "Количество отрицательных отзывов": 402313
    },
    {
        "id": 27,
        "Название": "Rag Doll Kung Fu",
        "Издатель": "Mark Healey",
        "Разработчик": "Mark Healey",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 5.99,
        "Количество положительных отзывов": 40,
        "Количество отрицательных отзывов": 17
    },
    {
        "id": 28,
        "Название": "Red Orchestra: Ostfront 41-45",
        "Издатель": "Tripwire Interactive",
        "Разработчик": "Tripwire Interactive",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Steam Achievements",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 1562,
        "Количество отрицательных отзывов": 223
    },
    {
        "id": 29,
        "Название": "Killing Floor",
        "Издатель": "Tripwire Interactive",
        "Разработчик": "Tripwire Interactive",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player, Steam Achievements, Steam Trading Cards, Cross-Platform Multiplayer, Stats, Includes level editor, Steam Workshop, Co-op",
        "Платформы": "windows, mac, linux",
        "Цена": 14.99,
        "Количество положительных отзывов": 53710,
        "Количество отрицательных отзывов": 2649
    },
    {
        "id": 30,
        "Название": "SiN Episodes: Emergence",
        "Издатель": "Ritual Entertainment",
        "Разработчик": "Ritual Entertainment",
        "Категории": "Single-player, Stats",
        "Платформы": "windows",
        "Цена": 7.19,
        "Количество положительных отзывов": 468,
        "Количество отрицательных отзывов": 61
    },
    {
        "id": 31,
        "Название": "Darwinia",
        "Издатель": "Introversion Software",
        "Разработчик": "Introversion Software",
        "Категории": "Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 472,
        "Количество отрицательных отзывов": 158
    },
    {
        "id": 32,
        "Название": "Uplink",
        "Издатель": "Introversion Software",
        "Разработчик": "Introversion Software",
        "Категории": "Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 6.99,
        "Количество положительных отзывов": 1602,
        "Количество отрицательных отзывов": 152
    },
    {
        "id": 33,
        "Название": "DEFCON",
        "Издатель": "Introversion Software",
        "Разработчик": "Introversion Software",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows, mac, linux",
        "Цена": 7.19,
        "Количество положительных отзывов": 2057,
        "Количество отрицательных отзывов": 344
    },
    {
        "id": 34,
        "Название": "Multiwinia",
        "Издатель": "Introversion Software",
        "Разработчик": "Introversion Software",
        "Категории": "Multi-player, Single-player, Steam Achievements",
        "Платформы": "windows, mac",
        "Цена": 7.19,
        "Количество положительных отзывов": 368,
        "Количество отрицательных отзывов": 75
    },
    {
        "id": 35,
        "Название": "Dangerous Waters",
        "Издатель": "Strategy First",
        "Разработчик": "Sonalysts",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 22.99,
        "Количество положительных отзывов": 140,
        "Количество отрицательных отзывов": 44
    },
    {
        "id": 36,
        "Название": "Space Empires IV Deluxe",
        "Издатель": "Strategy First",
        "Разработчик": "Malfador Machinations",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 6.99,
        "Количество положительных отзывов": 112,
        "Количество отрицательных отзывов": 26
    },
    {
        "id": 37,
        "Название": "Disciples II: Rise of the Elves ",
        "Издатель": "Strategy First",
        "Разработчик": "Strategy First",
        "Категории": "Multi-player, Single-player, Co-op",
        "Платформы": "windows",
        "Цена": 4.99,
        "Количество положительных отзывов": 451,
        "Количество отрицательных отзывов": 108
    },
    {
        "id": 38,
        "Название": "Disciples II: Gallean's Return",
        "Издатель": "Strategy First",
        "Разработчик": "Strategy First",
        "Категории": "Multi-player, Single-player, Co-op",
        "Платформы": "windows",
        "Цена": 4.99,
        "Количество положительных отзывов": 490,
        "Количество отрицательных отзывов": 152
    },
    {
        "id": 39,
        "Название": "Iron Warriors: T - 72 Tank Command ",
        "Издатель": "Strategy First",
        "Разработчик": "Strategy First",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 137,
        "Количество отрицательных отзывов": 102
    },
    {
        "id": 40,
        "Название": "Space Empires V",
        "Издатель": "Strategy First",
        "Разработчик": "Malfador Machinations",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 10.99,
        "Количество положительных отзывов": 191,
        "Количество отрицательных отзывов": 85
    },
    {
        "id": 41,
        "Название": "Arx Fatalis",
        "Издатель": "Arkane Studios",
        "Разработчик": "Arkane Studios",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 2.99,
        "Количество положительных отзывов": 671,
        "Количество отрицательных отзывов": 106
    },
    {
        "id": 42,
        "Название": "Source Filmmaker",
        "Издатель": "Valve",
        "Разработчик": "Valve",
        "Категории": "Steam Workshop",
        "Платформы": "windows",
        "Цена": 0,
        "Количество положительных отзывов": 15083,
        "Количество отрицательных отзывов": 1111
    },
    {
        "id": 43,
        "Название": "Earth 2160",
        "Издатель": "Topware Interactive;ACE",
        "Разработчик": "Reality Pump Studios",
        "Категории": "Multi-player, Single-player, Steam Trading Cards, Cross-Platform Multiplayer, Co-op",
        "Платформы": "windows, mac, linux",
        "Цена": 3.99,
        "Количество положительных отзывов": 498,
        "Количество отрицательных отзывов": 238
    },
    {
        "id": 44,
        "Название": "Two Worlds Epic Edition",
        "Издатель": "Topware Interactive",
        "Разработчик": "Reality Pump Studios",
        "Категории": "Multi-player, Online Multi-Player, Single-player, Steam Trading Cards, Partial Controller Support, Cross-Platform Multiplayer, Online Co-op",
        "Платформы": "windows, mac, linux",
        "Цена": 6.99,
        "Количество положительных отзывов": 2656,
        "Количество отрицательных отзывов": 1055
    },
    {
        "id": 45,
        "Название": "Dark Messiah of Might & Magic",
        "Издатель": "Ubisoft",
        "Разработчик": "Arkane Studios",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player",
        "Платформы": "windows",
        "Цена": 4.29,
        "Количество положительных отзывов": 4386,
        "Количество отрицательных отзывов": 316
    },
    {
        "id": 46,
        "Название": "Quake III Arena",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 12.99,
        "Количество положительных отзывов": 1362,
        "Количество отрицательных отзывов": 66
    },
    {
        "id": 47,
        "Название": "Quake IV",
        "Издатель": "Bethesda Softworks",
        "Разработчик": "RavenSoft / id Software",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 12.99,
        "Количество положительных отзывов": 891,
        "Количество отрицательных отзывов": 171
    },
    {
        "id": 48,
        "Название": "Wolfenstein 3D",
        "Издатель": "Bethesda-Softworks",
        "Разработчик": "id Software",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 2.99,
        "Количество положительных отзывов": 1773,
        "Количество отрицательных отзывов": 87
    },
    {
        "id": 49,
        "Название": "Ultimate Doom",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 3705,
        "Количество отрицательных отзывов": 257
    },
    {
        "id": 50,
        "Название": "Final DOOM",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 573,
        "Количество отрицательных отзывов": 82
    },
    {
        "id": 51,
        "Название": "DOOM II",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 2517,
        "Количество отрицательных отзывов": 182
    },
    {
        "id": 52,
        "Название": "QUAKE",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Multi-player, Single-player, Steam Cloud, Co-op",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 2618,
        "Количество отрицательных отзывов": 136
    },
    {
        "id": 53,
        "Название": "QUAKE II",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Multi-player, Single-player, Steam Cloud, Co-op",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 1369,
        "Количество отрицательных отзывов": 107
    },
    {
        "id": 54,
        "Название": "QUAKE II Mission Pack: The Reckoning",
        "Издатель": "id Software",
        "Разработчик": "Xatrix Entertainment",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 2.49,
        "Количество положительных отзывов": 65,
        "Количество отрицательных отзывов": 12
    },
    {
        "id": 55,
        "Название": "QUAKE II Mission Pack: Ground Zero",
        "Издатель": "id Software",
        "Разработчик": "Rogue Entertainment",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 2.49,
        "Количество положительных отзывов": 54,
        "Количество отрицательных отзывов": 33
    },
    {
        "id": 56,
        "Название": "QUAKE III: Team Arena",
        "Издатель": "id Software",
        "Разработчик": "id Software",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 12.99,
        "Количество положительных отзывов": 108,
        "Количество отрицательных отзывов": 31
    },
    {
        "id": 57,
        "Название": "HeXen: Beyond Heretic",
        "Издатель": "id Software",
        "Разработчик": "Raven Software",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 2.99,
        "Количество положительных отзывов": 249,
        "Количество отрицательных отзывов": 26
    },
    {
        "id": 58,
        "Название": "HeXen: Deathkings of the Dark Citadel",
        "Издатель": "id Software",
        "Разработчик": "Raven Software",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 2.99,
        "Количество положительных отзывов": 57,
        "Количество отрицательных отзывов": 20
    },
    {
        "id": 59,
        "Название": "Heretic: Shadow of the Serpent Riders",
        "Издатель": "id Software",
        "Разработчик": "Raven Software",
        "Категории": "Multi-player, Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 2.99,
        "Количество положительных отзывов": 417,
        "Количество отрицательных отзывов": 29
    },
    {
        "id": 60,
        "Название": "The Ship: Murder Party",
        "Издатель": "Blazing Griffin Ltd.",
        "Разработчик": "Outerlight Ltd.",
        "Категории": "Multi-player, Valve Anti-Cheat enabled, Single-player, Steam Trading Cards",
        "Платформы": "windows",
        "Цена": 0,
        "Количество положительных отзывов": 4819,
        "Количество отрицательных отзывов": 792
    },
    {
        "id": 61,
        "Название": "Bloody Good Time",
        "Издатель": "Ubisoft",
        "Разработчик": "Outerlight Ltd.",
        "Категории": "Multi-player, Single-player, Steam Achievements",
        "Платформы": "windows",
        "Цена": 4.29,
        "Количество положительных отзывов": 662,
        "Количество отрицательных отзывов": 204
    },
    {
        "id": 62,
        "Название": "Shadowgrounds",
        "Издатель": "Frozenbyte",
        "Разработчик": "Frozenbyte",
        "Категории": "Single-player, Steam Trading Cards, Shared/Split Screen",
        "Платформы": "windows, mac",
        "Цена": 3.99,
        "Количество положительных отзывов": 973,
        "Количество отрицательных отзывов": 248
    },
    {
        "id": 63,
        "Название": "Gumboy - Crazy Adventures™",
        "Издатель": "CINEMAX, s.r.o.",
        "Разработчик": "CINEMAX, s.r.o.",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 0,
        "Количество положительных отзывов": 52,
        "Количество отрицательных отзывов": 46
    },
    {
        "id": 64,
        "Название": "Alpha Prime",
        "Издатель": "Bohemia Interactive",
        "Разработчик": "Black Element",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 2.99,
        "Количество положительных отзывов": 610,
        "Количество отрицательных отзывов": 523
    },
    {
        "id": 65,
        "Название": "Vampire: The Masquerade - Bloodlines",
        "Издатель": "Activision",
        "Разработчик": "Troika Games",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 14.99,
        "Количество положительных отзывов": 6161,
        "Количество отрицательных отзывов": 362
    },
    {
        "id": 66,
        "Название": "GUN™",
        "Издатель": "Activision",
        "Разработчик": "Neversoft",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 9.99,
        "Количество положительных отзывов": 740,
        "Количество отрицательных отзывов": 87
    },
    {
        "id": 67,
        "Название": "Call of Duty®",
        "Издатель": "Activision",
        "Разработчик": "Infinity Ward",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 14.99,
        "Количество положительных отзывов": 1555,
        "Количество отрицательных отзывов": 117
    },
    {
        "id": 68,
        "Название": "Call of Duty® 2",
        "Издатель": "Activision;Aspyr (Mac)",
        "Разработчик": "Infinity Ward;Aspyr (Mac)",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows, mac",
        "Цена": 14.99,
        "Количество положительных отзывов": 2434,
        "Количество отрицательных отзывов": 236
    },
    {
        "id": 69,
        "Название": "Call of Duty: United Offensive",
        "Издатель": "Activision",
        "Разработчик": "Gray Matter Studios",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 14.99,
        "Количество положительных отзывов": 490,
        "Количество отрицательных отзывов": 97
    },
    {
        "id": 70,
        "Название": "Act of War: Direct Action",
        "Издатель": "THQ Nordic",
        "Разработчик": "Eugen Systems",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 1.99,
        "Количество положительных отзывов": 180,
        "Количество отрицательных отзывов": 33
    },
    {
        "id": 71,
        "Название": "ThreadSpace: Hyperbol",
        "Издатель": "Atari",
        "Разработчик": "Iocaine Studios",
        "Категории": "Multi-player, Single-player, Includes level editor",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 31,
        "Количество отрицательных отзывов": 9
    },
    {
        "id": 72,
        "Название": "ARMA: Combat Operations",
        "Издатель": "Bohemia Interactive",
        "Разработчик": "Bohemia Interactive",
        "Категории": "Multi-player, Single-player, Includes level editor",
        "Платформы": "windows",
        "Цена": 5.99,
        "Количество положительных отзывов": 145,
        "Количество отрицательных отзывов": 77
    },
    {
        "id": 73,
        "Название": "X2: The Threat",
        "Издатель": "Egosoft",
        "Разработчик": "Egosoft",
        "Категории": "Single-player, Steam Cloud, Captions available",
        "Платформы": "windows",
        "Цена": 4.99,
        "Количество положительных отзывов": 212,
        "Количество отрицательных отзывов": 50
    },
    {
        "id": 74,
        "Название": "X3: Reunion",
        "Издатель": "Egosoft",
        "Разработчик": "Egosoft",
        "Категории": "Single-player, Steam Cloud, Captions available",
        "Платформы": "windows, mac, linux",
        "Цена": 9.99,
        "Количество положительных отзывов": 282,
        "Количество отрицательных отзывов": 113
    },
    {
        "id": 75,
        "Название": "X3: Terran Conflict",
        "Издатель": "Egosoft",
        "Разработчик": "Egosoft",
        "Категории": "Single-player, Steam Cloud, Steam Achievements, Captions available, Full controller support",
        "Платформы": "windows, mac, linux",
        "Цена": 15.99,
        "Количество положительных отзывов": 1633,
        "Количество отрицательных отзывов": 272
    },
    {
        "id": 76,
        "Название": "X: Beyond the Frontier",
        "Издатель": "Egosoft",
        "Разработчик": "Egosoft",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 3.49,
        "Количество положительных отзывов": 142,
        "Количество отрицательных отзывов": 48
    },
    {
        "id": 77,
        "Название": "X: Tension",
        "Издатель": "Egosoft",
        "Разработчик": "Egosoft",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 3.49,
        "Количество положительных отзывов": 57,
        "Количество отрицательных отзывов": 18
    },
    {
        "id": 78,
        "Название": "X Rebirth",
        "Издатель": "Egosoft",
        "Разработчик": "Egosoft",
        "Категории": "Single-player, Steam Cloud, Steam Achievements, Steam Trading Cards, Captions available, Steam Workshop, Full controller support",
        "Платформы": "windows, mac, linux",
        "Цена": 24.99,
        "Количество положительных отзывов": 2832,
        "Количество отрицательных отзывов": 4032
    },
    {
        "id": 79,
        "Название": "688(I) Hunter/Killer",
        "Издатель": "Strategy First",
        "Разработчик": "Sonalysts",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 22.99,
        "Количество положительных отзывов": 52,
        "Количество отрицательных отзывов": 17
    },
    {
        "id": 80,
        "Название": "Fleet Command",
        "Издатель": "Strategy First",
        "Разработчик": "Sonalysts",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 22.99,
        "Количество положительных отзывов": 127,
        "Количество отрицательных отзывов": 31
    },
    {
        "id": 81,
        "Название": "Sub Command",
        "Издатель": "Strategy First",
        "Разработчик": "Sonalysts",
        "Категории": "Multi-player, Single-player, Includes level editor, Co-op",
        "Платформы": "windows",
        "Цена": 22.99,
        "Количество положительных отзывов": 33,
        "Количество отрицательных отзывов": 14
    },
    {
        "id": 82,
        "Название": "FlatOut 2™",
        "Издатель": "Strategy First",
        "Разработчик": "Bugbear Entertainment",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 5.99,
        "Количество положительных отзывов": 5438,
        "Количество отрицательных отзывов": 343
    },
    {
        "id": 83,
        "Название": "Xpand Rally",
        "Издатель": "Techland",
        "Разработчик": "Techland",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 139,
        "Количество отрицательных отзывов": 39
    },
    {
        "id": 84,
        "Название": "Call of Juarez™",
        "Издатель": "Techland Publishing",
        "Разработчик": "Techland",
        "Категории": "Multi-player, Single-player, Steam Trading Cards",
        "Платформы": "windows",
        "Цена": 8.59,
        "Количество положительных отзывов": 793,
        "Количество отрицательных отзывов": 198
    },
    {
        "id": 85,
        "Название": "Xpand Rally Xtreme",
        "Издатель": "Techland",
        "Разработчик": "Techland",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 71,
        "Количество отрицательных отзывов": 36
    },
    {
        "id": 86,
        "Название": "Men of War: Red Tide",
        "Издатель": "1C Entertainment;1C-SoftClub",
        "Разработчик": "1C Entertainment",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows",
        "Цена": 3.99,
        "Количество положительных отзывов": 294,
        "Количество отрицательных отзывов": 69
    },
    {
        "id": 87,
        "Название": "King's Bounty: Armored Princess",
        "Издатель": "1C Entertainment",
        "Разработчик": "Katauri Interactive",
        "Категории": "Single-player, Steam Cloud",
        "Платформы": "windows, mac",
        "Цена": 7.99,
        "Количество положительных отзывов": 482,
        "Количество отрицательных отзывов": 53
    },
    {
        "id": 88,
        "Название": "Genesis Rising",
        "Издатель": "THQ Nordic",
        "Разработчик": "Metamorf",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 4.49,
        "Количество положительных отзывов": 30,
        "Количество отрицательных отзывов": 94
    },
    {
        "id": 89,
        "Название": "Safecracker: The Ultimate Puzzle Adventure",
        "Издатель": "HandyGames",
        "Разработчик": "Kheops Studio",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.49,
        "Количество положительных отзывов": 256,
        "Количество отрицательных отзывов": 172
    },
    {
        "id": 90,
        "Название": "Painkiller Overdose",
        "Издатель": "THQ Nordic",
        "Разработчик": "Mindware Studios",
        "Категории": "Multi-player, Single-player",
        "Платформы": "windows",
        "Цена": 4.49,
        "Количество положительных отзывов": 429,
        "Количество отрицательных отзывов": 137
    },
    {
        "id": 91,
        "Название": "Zuma Deluxe",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "PopCap Games, Inc.",
        "Категории": "Single-player",
        "Платформы": "windows, mac",
        "Цена": 4.25,
        "Количество положительных отзывов": 437,
        "Количество отрицательных отзывов": 37
    },
    {
        "id": 92,
        "Название": "Heavy Weapon Deluxe",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "PopCap Games, Inc.",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.25,
        "Количество положительных отзывов": 71,
        "Количество отрицательных отзывов": 28
    },
    {
        "id": 93,
        "Название": "Peggle Deluxe",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "PopCap Games, Inc.",
        "Категории": "Single-player",
        "Платформы": "windows, mac",
        "Цена": 4.25,
        "Количество положительных отзывов": 1106,
        "Количество отрицательных отзывов": 66
    },
    {
        "id": 94,
        "Название": "Peggle Extreme",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "PopCap Games, Inc.",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 0,
        "Количество положительных отзывов": 707,
        "Количество отрицательных отзывов": 58
    },
    {
        "id": 95,
        "Название": "Venice Deluxe",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "Retro64, Inc.",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.25,
        "Количество положительных отзывов": 10,
        "Количество отрицательных отзывов": 2
    },
    {
        "id": 96,
        "Название": "Mystery P.I.™ - The Lottery Ticket",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "SpinTop Games",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.25,
        "Количество положительных отзывов": 10,
        "Количество отрицательных отзывов": 3
    },
    {
        "id": 97,
        "Название": "Amazing Adventures The Lost Tomb™",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "SpinTop Games",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.25,
        "Количество положительных отзывов": 21,
        "Количество отрицательных отзывов": 8
    },
    {
        "id": 98,
        "Название": "Mystery P.I.™ - The Vegas Heist",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "SpinTop Games",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.25,
        "Количество положительных отзывов": 11,
        "Количество отрицательных отзывов": 5
    },
    {
        "id": 99,
        "Название": "Amazing Adventures Around the World",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "SpinTop Games",
        "Категории": "Single-player",
        "Платформы": "windows",
        "Цена": 4.25,
        "Количество положительных отзывов": 23,
        "Количество отрицательных отзывов": 7
    },
    {
        "id": 100,
        "Название": "Peggle™ Nights",
        "Издатель": "PopCap Games, Inc.",
        "Разработчик": "PopCap Games, Inc.",
        "Категории": "Single-player",
        "Платформы": "windows, mac",
        "Цена": 4.25,
        "Количество положительных отзывов": 368,
        "Количество отрицательных отзывов": 24
    }
];

 
export default  games;
